questions = [
    {
        "question": "Quale vantaggio dello sviluppo iterativo è indicato nelle slide?",
        "options": [
            "Migliore produttività e minori difetti",
            "Eliminazione completa della documentazione",
            "Pianificazione dettagliata dell'intero progetto",
            "Assenza di iterazioni timeboxed",
        ],
        "correct_answer": "Migliore produttività e minori difetti",
        "source_quote": "• Migliore produttività e minori difetti",
        "source_file": "02-UP.pdf",
        "source_page": 5,
    },
    {
        "question": "Quale svantaggio dello sviluppo iterativo riguarda la visibilità per i manager?",
        "options": [
            "I manager non hanno visibilità sul processo di sviluppo dalla documentazione",
            "I manager devono scrivere tutti i test di accettazione",
            "I manager non possono partecipare alle milestone",
            "I manager devono cambiare team a ogni iterazione",
        ],
        "correct_answer": "I manager non hanno visibilità sul processo di sviluppo dalla documentazione",
        "source_quote": "• I manager non hanno visibilità sul processo di",
        "source_file": "02-UP.pdf",
        "source_page": 5,
    },
    {
        "question": "Nel modello iterativo plan-driven, quando vengono stabiliti gli incrementi?",
        "options": [
            "In anticipo",
            "Solo dopo il rilascio finale",
            "Durante la retrospettiva di sprint",
            "Solo quando il cliente è onsite",
        ],
        "correct_answer": "In anticipo",
        "source_quote": "• Plan-driven: gli incrementi sono stabiliti in",
        "source_file": "02-UP.pdf",
        "source_page": 6,
    },
    {
        "question": "Nel modello iterativo agile, quali incrementi vengono identificati inizialmente?",
        "options": [
            "Solo gli incrementi iniziali",
            "Tutti gli incrementi del progetto",
            "Solo gli incrementi architetturali finali",
            "Nessun incremento",
        ],
        "correct_answer": "Solo gli incrementi iniziali",
        "source_quote": "• Agile: si identificano solo gli incrementi iniziali",
        "source_file": "02-UP.pdf",
        "source_page": 6,
    },
    {
        "question": "Secondo le slide, quanto dovrebbero essere lunghe le iterazioni?",
        "options": [
            "Da 2 a 6 settimane",
            "Da 1 a 2 giorni",
            "Sempre 6 mesi",
            "Solo poche ore",
        ],
        "correct_answer": "Da 2 a 6 settimane",
        "source_quote": "   – Da 2 a 6 settimane",
        "source_file": "02-UP.pdf",
        "source_page": 6,
    },
    {
        "question": "Che tipo di processo è RUP/UP secondo le slide?",
        "options": [
            "Un processo di tipo iterativo",
            "Un processo esclusivamente a cascata",
            "Un processo senza pianificazione",
            "Un processo solo per test automatici",
        ],
        "correct_answer": "Un processo di tipo iterativo",
        "source_quote": "• Processo di tipo iterativo (agile)",
        "source_file": "02-UP.pdf",
        "source_page": 6,
    },
    {
        "question": "Nella fase di ideazione di UP, a quale domanda si risponde?",
        "options": [
            "Il progetto è fattibile?",
            "Quale IDE userà il team?",
            "Quale colore avrà l'interfaccia?",
            "Quanti test unitari saranno scritti a fine progetto?",
        ],
        "correct_answer": "Il progetto è fattibile?",
        "source_quote": "   – II progetto è fattibile?",
        "source_file": "02-UP.pdf",
        "source_page": 10,
    },
    {
        "question": "Durante l'elaborazione in UP, cosa viene sviluppato?",
        "options": [
            "Il nucleo",
            "Solo il manuale utente",
            "Solo il piano marketing",
            "La documentazione finale di collaudo",
        ],
        "correct_answer": "Il nucleo",
        "source_quote": "   – viene sviluppato il nucleo",
        "source_file": "02-UP.pdf",
        "source_page": 11,
    },
    {
        "question": "In UP, per quale iterazione si pianifica?",
        "options": [
            "Solo per l'iterazione successiva",
            "Per tutte le iterazioni in dettaglio",
            "Solo per l'ultima iterazione",
            "Per nessuna iterazione",
        ],
        "correct_answer": "Solo per l'iterazione successiva",
        "source_quote": "• Si pianifica solo per l’iterazione successiva",
        "source_file": "02-UP.pdf",
        "source_page": 12,
    },
    {
        "question": "Secondo le slide, in base a cosa si classifica il lavoro sui requisiti in UP?",
        "options": [
            "Rischio, criticità e copertura",
            "Costo dell'hardware, colore della UI e calendario",
            "Numero di sviluppatori, linguaggio e sistema operativo",
            "Anzianità del manager e dimensione dell'ufficio",
        ],
        "correct_answer": "Rischio, criticità e copertura",
        "source_quote": "  criticità e copertura",
        "source_file": "02-UP.pdf",
        "source_page": 12,
    },
    {
        "question": "Da cosa deriva il termine agile nelle slide?",
        "options": [
            "Dal manifesto agile",
            "Dal modello a cascata",
            "Da RUP di IBM",
            "Dal diagramma dei casi d'uso",
        ],
        "correct_answer": "Dal manifesto agile",
        "source_quote": "• Deriva dal manifesto agile http://agilemanifesto.org",
        "source_file": "03-XP.pdf",
        "source_page": 2,
    },
    {
        "question": "Che cosa descrive una storia utente nell'agile modeling?",
        "options": [
            "Una funzionalità o un requisito di interesse per il cliente",
            "Un diagramma UML completo e formale",
            "Un contratto di stato degli oggetti",
            "Una lista di difetti trovati nei test",
        ],
        "correct_answer": "Una funzionalità o un requisito di interesse per il cliente",
        "source_quote": "requisito che è di interesse per il cliente",
        "source_file": "03-XP.pdf",
        "source_page": 5,
    },
    {
        "question": "Cosa non contengono le storie utente secondo le slide?",
        "options": [
            "Dettagli sui requisiti",
            "Interesse per il cliente",
            "Una descrizione semplice",
            "Un promemoria per la pianificazione",
        ],
        "correct_answer": "Dettagli sui requisiti",
        "source_quote": "• Non contengono dettagli sui requisiti",
        "source_file": "03-XP.pdf",
        "source_page": 5,
    },
    {
        "question": "Che cos'è un'epopea nelle storie utente?",
        "options": [
            "Una storia composta da suddividere",
            "Una storia troppo piccola da combinare",
            "Un test di regressione automatico",
            "Una lavagna per il daily meeting",
        ],
        "correct_answer": "Una storia composta da suddividere",
        "source_quote": "• Epopea: storia composta da suddividere",
        "source_file": "03-XP.pdf",
        "source_page": 7,
    },
    {
        "question": "Secondo le linee guida, cosa succede alle storie troppo piccole?",
        "options": [
            "Sono combinate assieme",
            "Sono trasformate in epopee",
            "Sono scartate sempre",
            "Sono assegnate solo al product owner",
        ],
        "correct_answer": "Sono combinate assieme",
        "source_quote": "• Storie troppo piccole sono combinate assieme",
        "source_file": "03-XP.pdf",
        "source_page": 7,
    },
    {
        "question": "Quale criterio compare nelle linee guida per scrivere le storie?",
        "options": [
            "Chi, che cosa, e perché",
            "Dove, quando e con quale IDE",
            "Costo, colore e dimensione",
            "Classe, metodo e attributo privato",
        ],
        "correct_answer": "Chi, che cosa, e perché",
        "source_quote": "Chi, che cosa, e perché!",
        "source_file": "03-XP.pdf",
        "source_page": 7,
    },
    {
        "question": "In agile modeling, quanto conta la precisione nella notazione UML?",
        "options": [
            "Non importa",
            "È sempre obbligatoria",
            "Conta solo nei test di accettazione",
            "Conta solo nel product backlog",
        ],
        "correct_answer": "Non importa",
        "source_quote": "• La precisione nella notazione UML non importa",
        "source_file": "03-XP.pdf",
        "source_page": 9,
    },
    {
        "question": "Secondo le slide, quando UP può essere agile rispetto ai requisiti?",
        "options": [
            "Quando i requisiti emergono dai feedback durante la programmazione",
            "Quando tutti i requisiti sono congelati all'inizio",
            "Quando non si usano feedback",
            "Quando il piano dettagliato copre tutto il progetto",
        ],
        "correct_answer": "Quando i requisiti emergono dai feedback durante la programmazione",
        "source_quote": "• I requisiti emergono dai feedback durante la",
        "source_file": "03-XP.pdf",
        "source_page": 10,
    },
    {
        "question": "Su quali valori si basa Extreme Programming secondo la citazione nelle slide?",
        "options": [
            "Communication, simplicity, feedback and courage",
            "Inspection, transparency, estimation and release",
            "Planning, contracts, diagrams and governance",
            "Classes, attributes, associations and inheritance",
        ],
        "correct_answer": "Communication, simplicity, feedback and courage",
        "source_quote": "values of communication, simplicity, feedback and",
        "source_file": "03-XP.pdf",
        "source_page": 10,
    },
    {
        "question": "Nel simple design di Beck, qual è il primo requisito elencato?",
        "options": [
            "Appropriate for the intended audience",
            "Minimal",
            "Factored",
            "Communicative",
        ],
        "correct_answer": "Appropriate for the intended audience",
        "source_quote": "  1. Appropriate for the intended audience",
        "source_file": "03-XP.pdf",
        "source_page": 11,
    },
    {
        "question": "Secondo YAGNI, cosa dovrebbe supportare ciò che si progetta?",
        "options": [
            "Le storie utente",
            "Tutti i requisiti futuri immaginabili",
            "Solo i diagrammi UML finali",
            "La documentazione non mantenuta",
        ],
        "correct_answer": "Le storie utente",
        "source_quote": "  dovrebbe supportare le storie utente",
        "source_file": "03-XP.pdf",
        "source_page": 12,
    },
    {
        "question": "Nel test driven development, quando sono scritti i test?",
        "options": [
            "Prima che il task sia implementato",
            "Dopo il rilascio finale",
            "Solo durante la retrospettiva",
            "Quando il codice è già stabile",
        ],
        "correct_answer": "Prima che il task sia implementato",
        "source_quote": "I test sono scritti prima che",
        "source_file": "03-XP.pdf",
        "source_page": 14,
    },
    {
        "question": "Quale vantaggio del TDD riguarda la scoperta dei difetti?",
        "options": [
            "I difetti sono scoperti nelle prime fasi dello sviluppo",
            "I difetti sono ignorati fino alla consegna",
            "I difetti sono sempre corretti dal cliente",
            "I difetti non possono esistere",
        ],
        "correct_answer": "I difetti sono scoperti nelle prime fasi dello sviluppo",
        "source_quote": "• Difetti sono scoperti nelle prime fasi dello",
        "source_file": "03-XP.pdf",
        "source_page": 14,
    },
    {
        "question": "Che cosa fanno due sviluppatori nel pair programming?",
        "options": [
            "Lavorano alla stessa tastiera aiutandosi vicendevolmente",
            "Scrivono documentazione separata senza parlarsi",
            "Pianificano il product backlog da soli",
            "Disegnano solo diagrammi dei casi d'uso",
        ],
        "correct_answer": "Lavorano alla stessa tastiera aiutandosi vicendevolmente",
        "source_quote": "• Due sviluppatori lavorano alla stessa tastiera",
        "source_file": "03-XP.pdf",
        "source_page": 15,
    },
    {
        "question": "Nel pair programming, cosa usa il driver?",
        "options": [
            "La tastiera e il mouse",
            "Il product backlog",
            "La burndown chart",
            "Le schede CRC",
        ],
        "correct_answer": "La tastiera e il mouse",
        "source_quote": "• Il driver usa la tastiera e il mouse e codifica",
        "source_file": "03-XP.pdf",
        "source_page": 15,
    },
    {
        "question": "Quale obiettivo dell'integrazione continua è indicato nelle slide?",
        "options": [
            "Potere rilasciare quasi tutto in qualsiasi momento",
            "Rilasciare solo dopo molti mesi senza test",
            "Evitare l'integrazione del codice",
            "Bloccare il repository fino alla fine del progetto",
        ],
        "correct_answer": "Potere rilasciare quasi tutto in qualsiasi momento",
        "source_quote": "• L’obiettivo è potere rilasciare tutto (eccetto le ultime",
        "source_file": "03-XP.pdf",
        "source_page": 16,
    },
    {
        "question": "Nella proprietà collettiva, chi condivide la responsabilità per la qualità del codice?",
        "options": [
            "Tutti",
            "Solo il cliente",
            "Solo il manager",
            "Solo il driver",
        ],
        "correct_answer": "Tutti",
        "source_quote": "• Tutti condividono la responsabilità per la",
        "source_file": "03-XP.pdf",
        "source_page": 17,
    },
    {
        "question": "Quale difetto di XP è citato nelle slide?",
        "options": [
            "Carenza di documentazione",
            "Eccesso obbligatorio di diagrammi formali",
            "Impossibilità di fare pair programming",
            "Assenza di feedback",
        ],
        "correct_answer": "Carenza di documentazione",
        "source_quote": "• Carenza di documentazione",
        "source_file": "03-XP.pdf",
        "source_page": 20,
    },
    {
        "question": "Su quale teoria è fondata l'essenza di Scrum?",
        "options": [
            "Teoria dei processi empirici",
            "Teoria della decomposizione procedurale",
            "Teoria del modello a cascata puro",
            "Teoria delle classi concettuali",
        ],
        "correct_answer": "Teoria dei processi empirici",
        "source_quote": "• Fondato sulla teoria dei processi empirici",
        "source_file": "04-Scrum.pdf",
        "source_page": 2,
    },
    {
        "question": "In Scrum, cosa richiede la trasparenza?",
        "options": [
            "Che gli aspetti significativi del processo siano visibili ai responsabili del risultato",
            "Che il codice sia nascosto fino alla fine",
            "Che il product backlog sia privato",
            "Che le decisioni siano prese senza ispezione",
        ],
        "correct_answer": "Che gli aspetti significativi del processo siano visibili ai responsabili del risultato",
        "source_quote": "    devono essere visibili ai responsabili del risultato",
        "source_file": "04-Scrum.pdf",
        "source_page": 2,
    },
    {
        "question": "Chi è il product owner secondo le slide?",
        "options": [
            "La voce del cliente",
            "Il responsabile esclusivo dei test unitari",
            "Il membro che risolve solo problemi tecnici",
            "Il facilitatore della retrospettiva",
        ],
        "correct_answer": "La voce del cliente",
        "source_quote": "• È la voce del cliente",
        "source_file": "04-Scrum.pdf",
        "source_page": 4,
    },
    {
        "question": "Quale artefatto gestisce il product owner?",
        "options": [
            "Il product backlog",
            "Il codice sorgente di tutti gli sviluppatori",
            "Le schede CRC",
            "Il diagramma dei casi d'uso",
        ],
        "correct_answer": "Il product backlog",
        "source_quote": "• Gestisce il product backlog",
        "source_file": "04-Scrum.pdf",
        "source_page": 4,
    },
    {
        "question": "Secondo le slide, quanto è grande il team di sviluppo Scrum?",
        "options": [
            "6 professionisti (+/- 3)",
            "Sempre 2 persone",
            "Almeno 30 persone",
            "Un solo product owner",
        ],
        "correct_answer": "6 professionisti (+/- 3)",
        "source_quote": "• 6 professionisti (+/- 3)",
        "source_file": "04-Scrum.pdf",
        "source_page": 7,
    },
    {
        "question": "Che cosa caratterizza lo sprint come unità base di sviluppo?",
        "options": [
            "È time-boxed",
            "Ha durata casuale",
            "Non produce incrementi",
            "Non ha goal",
        ],
        "correct_answer": "È time-boxed",
        "source_quote": "  – Time-boxed",
        "source_file": "04-Scrum.pdf",
        "source_page": 8,
    },
    {
        "question": "Quanto dura tipicamente uno sprint secondo le slide?",
        "options": [
            "2-4 settimane",
            "Un giorno",
            "Un anno",
            "Solo poche ore",
        ],
        "correct_answer": "2-4 settimane",
        "source_quote": "  – Tipicamente 2-4 settimane",
        "source_file": "04-Scrum.pdf",
        "source_page": 8,
    },
    {
        "question": "Quando avviene lo sprint planning meeting?",
        "options": [
            "All'inizio di ogni sprint",
            "Solo alla fine del progetto",
            "Durante ogni commit",
            "Dopo la sprint review",
        ],
        "correct_answer": "All'inizio di ogni sprint",
        "source_quote": "• All’inizio di ogni sprint",
        "source_file": "04-Scrum.pdf",
        "source_page": 9,
    },
    {
        "question": "Quale domanda appartiene al daily scrum meeting?",
        "options": [
            "Stai avendo problemi?",
            "Quale classe concettuale è un attributo?",
            "Quale release è prevista tra cinque anni?",
            "Quale diagramma UML va archiviato?",
        ],
        "correct_answer": "Stai avendo problemi?",
        "source_quote": "3. Stai avendo problemi?",
        "source_file": "04-Scrum.pdf",
        "source_page": 11,
    },
    {
        "question": "Nel daily scrum meeting, quali discussioni sono permesse oltre alle tre domande?",
        "options": [
            "Nessuna altra discussione",
            "Solo discussioni di architettura lunghe",
            "Solo discussioni con gli stakeholder",
            "Tutte le discussioni richieste dal team",
        ],
        "correct_answer": "Nessuna altra discussione",
        "source_quote": "• Nessuna altra discussione è permessa",
        "source_file": "04-Scrum.pdf",
        "source_page": 11,
    },
    {
        "question": "Che cos'è lo sprint review meeting?",
        "options": [
            "Una demo del prodotto",
            "Una riunione per scrivere casi d'uso",
            "Un incontro solo per stimare task futuri",
            "Una fase di reverse-engineering UML",
        ],
        "correct_answer": "Una demo del prodotto",
        "source_quote": "• È una demo del prodotto",
        "source_file": "04-Scrum.pdf",
        "source_page": 13,
    },
    {
        "question": "Qual è lo scopo dello sprint retrospective meeting?",
        "options": [
            "Inspect & adapt the process",
            "Dimostrare le storie utente al cliente",
            "Definire tutte le feature del prodotto",
            "Scegliere i casi d'uso del modello OO",
        ],
        "correct_answer": "Inspect & adapt the process",
        "source_quote": "• Scopo: inspect & adapt the process",
        "source_file": "04-Scrum.pdf",
        "source_page": 14,
    },
    {
        "question": "Che cos'è il product backlog?",
        "options": [
            "Elenco di ciò che è necessario fare",
            "Elenco delle sole classi concettuali",
            "Grafico del lavoro rimanente",
            "Contratto con post-condizioni",
        ],
        "correct_answer": "Elenco di ciò che è necessario fare",
        "source_quote": "• Elenco di ciò che è necessario fare",
        "source_file": "04-Scrum.pdf",
        "source_page": 16,
    },
    {
        "question": "Che cos'è lo sprint backlog?",
        "options": [
            "Elenco di attività da completare entro lo Sprint",
            "Elenco di stakeholder del prodotto",
            "Documento di testo dei casi d'uso",
            "Diagramma di interazione",
        ],
        "correct_answer": "Elenco di attività da completare entro lo Sprint",
        "source_quote": "• Elenco di attività da completare entro lo Sprint",
        "source_file": "04-Scrum.pdf",
        "source_page": 17,
    },
    {
        "question": "Che cosa mostra una burndown chart?",
        "options": [
            "Come sta andando lo Sprint",
            "Gli attori dei casi d'uso",
            "Le responsabilità delle schede CRC",
            "I requisiti non funzionali come storie",
        ],
        "correct_answer": "Come sta andando lo Sprint",
        "source_quote": "• Mostra come sta andando lo Sprint",
        "source_file": "04-Scrum.pdf",
        "source_page": 19,
    },
    {
        "question": "Quando Scrum non funziona secondo una voce delle slide?",
        "options": [
            "Con squadre troppo piccole",
            "Con sprint time-boxed",
            "Con product backlog visibile",
            "Con daily scrum meeting",
        ],
        "correct_answer": "Con squadre troppo piccole",
        "source_quote": "• Squadre troppo piccole (fino a tre persone)",
        "source_file": "04-Scrum.pdf",
        "source_page": 21,
    },
    {
        "question": "Nel paradigma OO, che cosa fa OOA?",
        "options": [
            "Esamina e decompone il problema",
            "Realizza il modello",
            "Disegna il modello del problema",
            "Gestisce il product backlog",
        ],
        "correct_answer": "Esamina e decompone il problema",
        "source_quote": "  – OOA: Esamina e decompone il problema",
        "source_file": "05-OO.pdf",
        "source_page": 2,
    },
    {
        "question": "Che cosa sono i casi d'uso secondo le slide?",
        "options": [
            "Documenti di testo",
            "Diagrammi obbligatori",
            "Grafici burndown",
            "Carte CRC",
        ],
        "correct_answer": "Documenti di testo",
        "source_quote": "• Sono documenti di testo (non diagrammi!)",
        "source_file": "05-OO.pdf",
        "source_page": 3,
    },
    {
        "question": "In UP, quale ruolo hanno i casi d'uso rispetto ai requisiti?",
        "options": [
            "Sono il meccanismo per definire i requisiti",
            "Sono usati solo per stimare lo sprint",
            "Sono un sostituto della retrospettiva",
            "Sono grafici del lavoro rimanente",
        ],
        "correct_answer": "Sono il meccanismo per definire i requisiti",
        "source_quote": "• In UP sono il meccanismo per definire i requisiti",
        "source_file": "05-OO.pdf",
        "source_page": 3,
    },
    {
        "question": "Che cosa illustra un diagramma dei casi d'uso?",
        "options": [
            "Gli attori dei casi d'uso e le relazioni tra essi",
            "La quantità di lavoro rimanente",
            "Le post-condizioni dei contratti",
            "I task assegnati volontariamente",
        ],
        "correct_answer": "Gli attori dei casi d'uso e le relazioni tra essi",
        "source_quote": "• Illustra gli attori dei casi",
        "source_file": "05-OO.pdf",
        "source_page": 4,
    },
    {
        "question": "Che cosa non è il modello di dominio?",
        "options": [
            "Una raffigurazione degli oggetti software",
            "Un aiuto per comprendere il dominio",
            "Una fonte di ispirazione alla progettazione",
            "Un modello che evolve in modo incrementale",
        ],
        "correct_answer": "Una raffigurazione degli oggetti software",
        "source_quote": "• Non è una raffigurazione degli oggetti software",
        "source_file": "05-OO.pdf",
        "source_page": 7,
    },
    {
        "question": "Perché creare un modello di dominio?",
        "options": [
            "Per comprendere il dominio e il suo vocabolario",
            "Per sostituire tutti i test",
            "Per evitare le iterazioni",
            "Per fissare lo sprint goal",
        ],
        "correct_answer": "Per comprendere il dominio e il suo vocabolario",
        "source_quote": "1. Comprendere il dominio e il suo vocabolario",
        "source_file": "05-OO.pdf",
        "source_page": 8,
    },
    {
        "question": "Qual è il primo passo per creare il modello di dominio?",
        "options": [
            "Elencare le classi concettuali",
            "Aggiornare la burndown chart",
            "Scrivere il codice prima dei test",
            "Chiudere la discussione del product owner",
        ],
        "correct_answer": "Elencare le classi concettuali",
        "source_quote": "1. Elencare le classi concettuali",
        "source_file": "05-OO.pdf",
        "source_page": 9,
    },
    {
        "question": "Quale linea guida è indicata per trovare le classi concettuali?",
        "options": [
            "Utilizzare nomi esistenti sul territorio",
            "Aggiungere cose che non ci sono",
            "Richiedere la perfezione al primo tentativo",
            "Evitare i nomi usati nel dominio",
        ],
        "correct_answer": "Utilizzare nomi esistenti sul territorio",
        "source_quote": "• Utilizzare nomi esistenti sul territorio",
        "source_file": "05-OO.pdf",
        "source_page": 10,
    },
    {
        "question": "Quali attributi sono utili secondo le slide?",
        "options": [
            "Quelli suggeriti dai casi d'uso",
            "Quelli inventati senza dati da ricordare",
            "Quelli del product backlog",
            "Quelli della burndown chart",
        ],
        "correct_answer": "Quelli suggeriti dai casi d'uso",
        "source_quote": "• Sono utili quelli suggeriti dai casi d’uso",
        "source_file": "05-OO.pdf",
        "source_page": 11,
    },
    {
        "question": "Che cosa mostra un SSD per un caso d'uso?",
        "options": [
            "Gli eventi tra gli attori e il sistema e tra sistemi",
            "Solo il valore di mercato delle feature",
            "Le sedie del pair programming",
            "Le stime aggiornate della burndown chart",
        ],
        "correct_answer": "Gli eventi tra gli attori e il sistema e tra sistemi",
        "source_quote": "                  gli attori e il sistema e tra sistemi",
        "source_file": "05-OO.pdf",
        "source_page": 13,
    },
    {
        "question": "Che cosa descrivono i contratti?",
        "options": [
            "I cambiamenti di stato degli oggetti del modello di dominio tramite post condizioni",
            "La durata dello sprint planning meeting",
            "La voce del cliente",
            "La pianificazione approssimativa dell'iterazione",
        ],
        "correct_answer": "I cambiamenti di stato degli oggetti del modello di dominio tramite post condizioni",
        "source_quote": "• Descrivono i cambiamenti di stato degli oggetti del",
        "source_file": "05-OO.pdf",
        "source_page": 14,
    },
    {
        "question": "Nell'agile modeling OO, quando si dedica tempo al disegno UML?",
        "options": [
            "All'inizio dell'iterazione",
            "Solo dopo la consegna finale",
            "Durante ogni daily scrum",
            "Mai",
        ],
        "correct_answer": "All'inizio dell'iterazione",
        "source_quote": "              1. All’inizio dell’iterazione dedicare alcune ore al disegno UML",
        "source_file": "05-OO.pdf",
        "source_page": 17,
    },
    {
        "question": "Che cos'è RDD secondo le slide?",
        "options": [
            "Una metafora",
            "Un grafico dello sprint",
            "Una riunione giornaliera",
            "Un elenco di attività dello sprint",
        ],
        "correct_answer": "Una metafora",
        "source_quote": "• RDD è una metafora",
        "source_file": "05-OO.pdf",
        "source_page": 18,
    },
    {
        "question": "In RDD, come sono visti gli oggetti software nella metafora?",
        "options": [
            "Come persone che hanno responsabilità e collaborano con altri",
            "Come righe del product backlog",
            "Come slide da archiviare",
            "Come test scritti dopo il codice",
        ],
        "correct_answer": "Come persone che hanno responsabilità e collaborano con altri",
        "source_quote": "   – Oggetti software come persone che hanno responsabilità e",
        "source_file": "05-OO.pdf",
        "source_page": 18,
    },
    {
        "question": "Quale principio per RDD promuove dati e comportamenti correlati insieme?",
        "options": [
            "Promuovere l'incapsulamento",
            "Evitare ogni collaborazione",
            "Rendere gli oggetti meno smart",
            "Separare sempre dati e comportamento",
        ],
        "correct_answer": "Promuovere l'incapsulamento",
        "source_quote": "• Promuovere l’incapsulamento",
        "source_file": "05-OO.pdf",
        "source_page": 19,
    },
    {
        "question": "Che cosa significa CRC nelle schede CRC?",
        "options": [
            "Classe, Responsabilità, Collaborazione",
            "Cliente, Release, Codice",
            "Contratto, Requisito, Cliente",
            "Classe, Refactoring, Commit",
        ],
        "correct_answer": "Classe, Responsabilità, Collaborazione",
        "source_quote": "• Classe, Responsabilità, Collaborazione",
        "source_file": "05-OO.pdf",
        "source_page": 20,
    },
]
