questions_v2 = [
    {
        "question": "Che cosa può provare il testing secondo la citazione di Dijkstra?",
        "options": [
            "La presenza di errori in un programma",
            "L'assenza assoluta di errori",
            "La correttezza di ogni requisito futuro",
            "L'impossibilità di introdurre regressioni",
        ],
        "correct_answer": "La presenza di errori in un programma",
        "source_quote": " presenza di errori in un programma, mai",
        "source_file": "10-Testing.pdf",
        "source_page": 2,
    },
    {
        "question": "A cosa servono i test dello sviluppo?",
        "options": [
            "A scoprire bug durante lo sviluppo",
            "A decidere il pagamento finale",
            "A sostituire la documentazione dei requisiti",
            "A validare esclusivamente l'ambiente dell'utente",
        ],
        "correct_answer": "A scoprire bug durante lo sviluppo",
        "source_quote": "   – Condotti durante lo sviluppo per scoprire bug",
        "source_file": "10-Testing.pdf",
        "source_page": 2,
    },
    {
        "question": "Qual è lo scopo dei test della release?",
        "options": [
            "Verificare che il sistema soddisfi i requisiti",
            "Provare soltanto singoli metodi",
            "Calcolare la complessità di Halstead",
            "Ristrutturare il codice esistente",
        ],
        "correct_answer": "Verificare che il sistema soddisfi i requisiti",
        "source_quote": "   – Per verificare che il sistema soddisfa i requisiti",
        "source_file": "10-Testing.pdf",
        "source_page": 2,
    },
    {
        "question": "Dove provano il sistema gli utenti durante i test degli utenti?",
        "options": [
            "Nel loro ambiente",
            "Solo nel repository degli sviluppatori",
            "Esclusivamente in un flow graph",
            "Nel costruttore della classe",
        ],
        "correct_answer": "Nel loro ambiente",
        "source_quote": "   – Gli utenti provano il sistema nel loro ambiente",
        "source_file": "10-Testing.pdf",
        "source_page": 2,
    },
    {
        "question": "Con quale metodologia è stato introdotto il TDD?",
        "options": ["XP", "Scrum", "Modello a cascata", "Reverse engineering"],
        "correct_answer": "XP",
        "source_quote": "• Introdotto con XP ma oggi ampiamente utilizzato",
        "source_file": "10-Testing.pdf",
        "source_page": 3,
    },
    {
        "question": "Che tipo di ambiente richiede il TDD?",
        "options": [
            "Un ambiente di testing automatico",
            "Un ambiente privo di test",
            "Solo un ambiente di produzione",
            "Un ambiente esclusivamente manuale",
        ],
        "correct_answer": "Un ambiente di testing automatico",
        "source_quote": "• Richiede un ambiente di testing automatica, es. Junit",
        "source_file": "10-Testing.pdf",
        "source_page": 3,
    },
    {
        "question": "Secondo la prima regola del TDD, cosa deve precedere il codice di produzione?",
        "options": [
            "Un test di unità che fallisce",
            "Una release completa",
            "Un test beta",
            "Un documento di manutenzione",
        ],
        "correct_answer": "Un test di unità che fallisce",
        "source_quote": "1.   Non è possibile scrivere alcun codice di produzione, finché non si è",
        "source_file": "10-Testing.pdf",
        "source_page": 3,
    },
    {
        "question": "Quale vantaggio del TDD è riportato nelle slide?",
        "options": [
            "Permette test di regressione",
            "Elimina la necessità di automazione",
            "Rende inutili i test di unità",
            "Garantisce l'assenza di errori",
        ],
        "correct_answer": "Permette test di regressione",
        "source_quote": "Permette test di regressione",
        "source_file": "10-Testing.pdf",
        "source_page": 4,
    },
    {
        "question": "Quando il TDD è indicato come impraticabile?",
        "options": [
            "Quando si riusano grossi componenti o sistemi ereditati",
            "Quando si scrivono test automatizzati",
            "Quando si provano condizioni limite",
            "Quando il codice è nuovo",
        ],
        "correct_answer": "Quando si riusano grossi componenti o sistemi ereditati",
        "source_quote": "Impraticabile quando si riusano",
        "source_file": "10-Testing.pdf",
        "source_page": 4,
    },
    {
        "question": "Che cosa viene provato nei test delle unità?",
        "options": [
            "Le singole unità di programma o classi di oggetti",
            "Solo il sistema completo nell'ambiente utente",
            "Soltanto le interfacce tra aziende",
            "Esclusivamente il database globale",
        ],
        "correct_answer": "Le singole unità di programma o classi di oggetti",
        "source_quote": "   – Sono provate le singole unità di programma o classi di oggetti",
        "source_file": "10-Testing.pdf",
        "source_page": 4,
    },
    {
        "question": "Come sono chiamati anche i test dei componenti?",
        "options": [
            "Integration Testing",
            "Acceptance Testing",
            "Alpha Testing",
            "Inventory Analysis",
        ],
        "correct_answer": "Integration Testing",
        "source_quote": "• Test dei componenti (detto anche Integration Testing)",
        "source_file": "10-Testing.pdf",
        "source_page": 4,
    },
    {
        "question": "Che cosa verificano i test del sistema?",
        "options": [
            "Le interazioni tra i componenti",
            "Solo il valore degli attributi di una classe",
            "Soltanto la sintassi del codice",
            "Le responsabilità del product owner",
        ],
        "correct_answer": "Le interazioni tra i componenti",
        "source_quote": "     diversi team) per verificare le interazioni tra i componenti",
        "source_file": "10-Testing.pdf",
        "source_page": 4,
    },
    {
        "question": "Quale attività è richiesta quando si testano le classi?",
        "options": [
            "Testare tutte le operazioni associate a un oggetto",
            "Testare una sola operazione per gerarchia",
            "Ignorare gli attributi dell'oggetto",
            "Evitare le transizioni di stato",
        ],
        "correct_answer": "Testare tutte le operazioni associate a un oggetto",
        "source_quote": " • Testare tutte le operazioni associate a un oggetto",
        "source_file": "10-Testing.pdf",
        "source_page": 6,
    },
    {
        "question": "Come incide l'ereditarietà sul test di un metodo della superclasse?",
        "options": [
            "Il metodo va testato nel contesto di ogni sottoclasse",
            "Il metodo non deve più essere testato",
            "Basta testare una sottoclasse casuale",
            "Va testato solo nel contesto del driver",
        ],
        "correct_answer": "Il metodo va testato nel contesto di ogni sottoclasse",
        "source_quote": "    Ø Occorre testare X nel contesto di ogni sottoclasse",
        "source_file": "10-Testing.pdf",
        "source_page": 6,
    },
    {
        "question": "Cosa è opportuno usare per dipendenze non implementate o costose?",
        "options": [
            "Oggetti finti (mock)",
            "Solo test beta",
            "Un type code",
            "Un factory method",
        ],
        "correct_answer": "Oggetti finti (mock)",
        "source_quote": "oggetti finti (mock)",
        "source_file": "10-Testing.pdf",
        "source_page": 7,
    },
    {
        "question": "Su cosa si basa il testing black box?",
        "options": [
            "Sulle specifiche del modulo o sistema",
            "Sul codice del modulo",
            "Sulla struttura interna del flow graph",
            "Sui soli nodi predicato",
        ],
        "correct_answer": "Sulle specifiche del modulo o sistema",
        "source_quote": "• Black box (o funzionale): basato sulle specifiche del",
        "source_file": "10-Testing.pdf",
        "source_page": 7,
    },
    {
        "question": "Su cosa si basa il testing white box?",
        "options": [
            "Sul codice del modulo",
            "Solo sui requisiti esterni",
            "Sulle opinioni degli utenti beta",
            "Sul costo della manutenzione",
        ],
        "correct_answer": "Sul codice del modulo",
        "source_quote": "• White box (o strutturale): basato sul codice del",
        "source_file": "10-Testing.pdf",
        "source_page": 7,
    },
    {
        "question": "Che cosa chiede la function coverage?",
        "options": [
            "Se è stata richiamata ogni funzione del programma",
            "Se ogni valore limite è al centro dell'intervallo",
            "Se tutti gli utenti hanno eseguito un beta test",
            "Se ogni classe ha una sola responsabilità",
        ],
        "correct_answer": "Se è stata richiamata ogni funzione del programma",
        "source_quote": "• Function coverage: è stata richiamata ogni funzione del",
        "source_file": "10-Testing.pdf",
        "source_page": 9,
    },
    {
        "question": "Che cosa verifica la path coverage o branch coverage?",
        "options": [
            "Che ogni ramo delle strutture di controllo sia stato eseguito",
            "Che ogni funzione abbia un commento",
            "Che ogni requisito abbia un mock",
            "Che ogni modulo abbia fan-out nullo",
        ],
        "correct_answer": "Che ogni ramo delle strutture di controllo sia stato eseguito",
        "source_quote": "• Path coverage (o branch coverage): ogni ramo di",
        "source_file": "10-Testing.pdf",
        "source_page": 9,
    },
    {
        "question": "Che cosa rappresentano i nodi di un flow graph?",
        "options": [
            "Una o più istruzioni",
            "I requisiti non funzionali",
            "Gli utenti del sistema",
            "Le release del prodotto",
        ],
        "correct_answer": "Una o più istruzioni",
        "source_quote": "• Nodi: rappresentano una o più istruzioni",
        "source_file": "10-Testing.pdf",
        "source_page": 10,
    },
    {
        "question": "Che cosa misura la complessità ciclomatica?",
        "options": [
            "Il numero di cammini indipendenti nell'insieme di base",
            "Il numero di utenti beta",
            "Il numero di requisiti stabili",
            "Il numero di classi di equivalenza valide",
        ],
        "correct_answer": "Il numero di cammini indipendenti nell'insieme di base",
        "source_quote": "• La complessità ciclomatica è il numero di cammini",
        "source_file": "10-Testing.pdf",
        "source_page": 11,
    },
    {
        "question": "Che tipo di tecnica è l'ispezione del software?",
        "options": [
            "Una tecnica statica di verifica",
            "Una tecnica dinamica che richiede sempre l'esecuzione",
            "Una forma di stress testing",
            "Una variante del beta test",
        ],
        "correct_answer": "Una tecnica statica di verifica",
        "source_quote": "• Tecnica statica di verifica (non occorre eseguire il codice)",
        "source_file": "10-Testing.pdf",
        "source_page": 15,
    },
    {
        "question": "Che cosa rappresenta una classe di equivalenza?",
        "options": [
            "Stati validi o non validi per le condizioni di input",
            "Solo cammini indipendenti del codice",
            "Soltanto funzioni già richiamate",
            "Moduli che chiamano lo stesso componente",
        ],
        "correct_answer": "Stati validi o non validi per le condizioni di input",
        "source_quote": "• Una classe di equivalenza rappresenta stati validi o non",
        "source_file": "10-Testing.pdf",
        "source_page": 18,
    },
    {
        "question": "In cosa consiste il testing per regressione?",
        "options": [
            "Rieseguire test già condotti per controllare gli effetti delle modifiche",
            "Eseguire solo test mai usati prima",
            "Provare soltanto il carico massimo",
            "Sostituire tutti i test con ispezioni manuali",
        ],
        "correct_answer": "Rieseguire test già condotti per controllare gli effetti delle modifiche",
        "source_quote": "• Rieseguire test già condotti al fine di garantire",
        "source_file": "10-Testing.pdf",
        "source_page": 27,
    },
    {
        "question": "Quali sono le due attività della metafora dei due cappelli?",
        "options": [
            "Aggiungere funzionalità e fare refactoring",
            "Testing black box e testing white box",
            "Analisi e manutenzione preventiva",
            "Reverse engineering e stress testing",
        ],
        "correct_answer": "Aggiungere funzionalità e fare refactoring",
        "source_quote": "        • aggiungere funzionalità",
        "source_file": "11-Refactoring.pdf",
        "source_page": 2,
    },
    {
        "question": "Che cosa si fa indossando il cappello del refactoring?",
        "options": [
            "Si ristruttura il codice esistente",
            "Si aggiungono funzionalità e nuovi test",
            "Si modifica il requisito del cliente",
            "Si esegue soltanto il beta test",
        ],
        "correct_answer": "Si ristruttura il codice esistente",
        "source_quote": "             – Si ristruttura semplicemente il codice esistente",
        "source_file": "11-Refactoring.pdf",
        "source_page": 2,
    },
    {
        "question": "Cosa fare prima di aggiungere una funzionalità se il codice non è strutturato convenientemente?",
        "options": [
            "Prima rifattorizzare e poi aggiungere",
            "Copiare sempre il metodo esistente",
            "Eliminare tutti i test",
            "Rinviare ogni modifica alla manutenzione",
        ],
        "correct_answer": "Prima rifattorizzare e poi aggiungere",
        "source_quote": "                       questa aggiunta, prima rifattorizza e poi aggiungi",
        "source_file": "11-Refactoring.pdf",
        "source_page": 4,
    },
    {
        "question": "Quale beneficio del refactoring riguarda la progettazione?",
        "options": [
            "Migliora il design del software",
            "Elimina ogni costo di manutenzione",
            "Garantisce prestazioni massime senza misurazioni",
            "Sostituisce il testing di regressione",
        ],
        "correct_answer": "Migliora il design del software",
        "source_quote": "          • Migliora il design del software, e questo rende più",
        "source_file": "11-Refactoring.pdf",
        "source_page": 12,
    },
    {
        "question": "Quando va fatto il refactoring secondo le slide?",
        "options": [
            "Continuamente a brevi tratti",
            "Solo alla fine del progetto",
            "Soltanto dopo una release fallita",
            "Mai durante la correzione dei bug",
        ],
        "correct_answer": "Continuamente a brevi tratti",
        "source_quote": "Continuamente a brevi tratti!",
        "source_file": "11-Refactoring.pdf",
        "source_page": 13,
    },
    {
        "question": "Quando le slide suggeriscono di non fare refactoring?",
        "options": [
            "Quando è più facile riscrivere il codice da zero",
            "Quando si aggiunge una funzione",
            "Quando si revisiona il codice",
            "Quando si dispone di test automatici",
        ],
        "correct_answer": "Quando è più facile riscrivere il codice da zero",
        "source_quote": "• Quando è più facile riscrivere il codice da zero",
        "source_file": "11-Refactoring.pdf",
        "source_page": 13,
    },
    {
        "question": "Come si individuano le parti da ottimizzare nell'approccio consigliato?",
        "options": [
            "Usando un profiler",
            "Ottimizzando ogni modulo in anticipo",
            "Eliminando i test automatici",
            "Misurando soltanto le linee di commento",
        ],
        "correct_answer": "Usando un profiler",
        "source_quote": "     profiler per identificare le parti più costose, si ottimizzano",
        "source_file": "11-Refactoring.pdf",
        "source_page": 14,
    },
    {
        "question": "Quale fonte di puzza del codice viola il principio Don't repeat yourself?",
        "options": [
            "Codice duplicato",
            "Un factory method",
            "Una classe di equivalenza",
            "Un test alpha",
        ],
        "correct_answer": "Codice duplicato",
        "source_quote": "• Codice duplicato",
        "source_file": "11-Refactoring.pdf",
        "source_page": 14,
    },
    {
        "question": "Quale code smell è associato a procedure difficili da capire?",
        "options": [
            "Metodi troppo lunghi e non coesi",
            "Metodi con nomi chiari",
            "Classi con una sola responsabilità",
            "Test completamente automatizzati",
        ],
        "correct_answer": "Metodi troppo lunghi e non coesi",
        "source_quote": "• Metodi troppo lunghi e non coesi (~ più di 30 linee)",
        "source_file": "11-Refactoring.pdf",
        "source_page": 15,
    },
    {
        "question": "Quale principio viene violato quando una classe cambia per troppe ragioni?",
        "options": [
            "Single-responsibility principle",
            "Equivalence partitioning",
            "Function coverage",
            "Inventory analysis",
        ],
        "correct_answer": "Single-responsibility principle",
        "source_quote": "   – Capita quando si viola il single-responsibility principle!",
        "source_file": "11-Refactoring.pdf",
        "source_page": 16,
    },
    {
        "question": "Quale code smell nasce pensando a capacità future che forse non serviranno?",
        "options": [
            "Generalità puramente speculativa",
            "Codice duplicato",
            "Liste di parametri troppo lunghe",
            "Classi di equivalenza non valide",
        ],
        "correct_answer": "Generalità puramente speculativa",
        "source_quote": "• Generalità puramente speculativa",
        "source_file": "11-Refactoring.pdf",
        "source_page": 17,
    },
    {
        "question": "Come devono essere i test a supporto del refactoring?",
        "options": [
            "Completamente automatizzati e capaci di verificare i propri risultati",
            "Solo manuali e controllati a vista",
            "Eseguiti soltanto alla consegna",
            "Limitati ai test beta",
        ],
        "correct_answer": "Completamente automatizzati e capaci di verificare i propri risultati",
        "source_quote": "   Rendi i test completamente automatizzati e fai in",
        "source_file": "11-Refactoring.pdf",
        "source_page": 17,
    },
    {
        "question": "Quando si applica Extract Method?",
        "options": [
            "Quando un frammento di codice può essere raggruppato",
            "Quando serve aumentare il fan-out",
            "Quando si vuole eliminare una superclasse",
            "Quando si prepara un alpha test",
        ],
        "correct_answer": "Quando un frammento di codice può essere raggruppato",
        "source_quote": "  Un frammento di codice può essere raggruppato",
        "source_file": "11-Refactoring.pdf",
        "source_page": 19,
    },
    {
        "question": "Qual è la situazione di Replace Type Code with Subclasses?",
        "options": [
            "Una classe contiene una codifica esplicita dei tipi",
            "Una classe non contiene attributi",
            "Un metodo ritorna un valore senza cambiare stato",
            "Due moduli hanno fan-in basso",
        ],
        "correct_answer": "Una classe contiene una codifica esplicita dei tipi",
        "source_quote": "   Una classe contiene “type code”, ovvero la codifica esplicita",
        "source_file": "11-Refactoring.pdf",
        "source_page": 28,
    },
    {
        "question": "Quando è utile Replace Constructor with Factory Method?",
        "options": [
            "Quando si vuole fare più di una semplice costruzione dell'oggetto",
            "Quando si vuole misurare la branch coverage",
            "Quando si vuole mantenere un costruttore pubblico obbligatorio",
            "Quando si vogliono evitare sottoclassi",
        ],
        "correct_answer": "Quando si vuole fare più di una semplice costruzione dell'oggetto",
        "source_quote": "   Quando si crea un oggetto si vuole far più che una semplice",
        "source_file": "11-Refactoring.pdf",
        "source_page": 33,
    },
    {
        "question": "Quale problema affronta Duplicate Observed Data?",
        "options": [
            "Dati di dominio disponibili solo nello strato UI",
            "Test di unità non compilabili",
            "Cammini indipendenti mancanti",
            "Troppi utenti nel beta test",
        ],
        "correct_answer": "Dati di dominio disponibili solo nello strato UI",
        "source_quote": "     Dati sulla logica di dominio sono disponibili solo nello strato",
        "source_file": "11-Refactoring.pdf",
        "source_page": 37,
    },
    {
        "question": "Quando si usa Replace Method with Method Object?",
        "options": [
            "Quando le variabili locali impediscono di usare Extract Method",
            "Quando non esistono variabili locali",
            "Quando il metodo è già breve",
            "Quando serve un test di release",
        ],
        "correct_answer": "Quando le variabili locali impediscono di usare Extract Method",
        "source_quote": "  Un metodo lungo usa variabili locali in un modo tale che non",
        "source_file": "12-Refactoring-Addon.pdf",
        "source_page": 2,
    },
    {
        "question": "Quale situazione motiva Hide Delegate?",
        "options": [
            "Un client chiama un metodo di un delegate memorizzato dal server",
            "Un metodo non ha parametri",
            "Due sottoclassi producono risultati diversi",
            "Un dato non richiede comportamenti",
        ],
        "correct_answer": "Un client chiama un metodo di un delegate memorizzato dal server",
        "source_quote": "  Un client sta chiamando un metodo di un oggetto (delegate)",
        "source_file": "12-Refactoring-Addon.pdf",
        "source_page": 5,
    },
    {
        "question": "Quando si usa Introduce Foreign Method?",
        "options": [
            "Quando una classe server necessita di un metodo ma non può essere modificata",
            "Quando il server espone già troppi metodi deleganti",
            "Quando si vuole rimuovere una classe server",
            "Quando si misura la complessità ciclomatica",
        ],
        "correct_answer": "Quando una classe server necessita di un metodo ma non può essere modificata",
        "source_quote": "  Una classe Server ha bisogno di un metodo aggiuntivo, ma",
        "source_file": "12-Refactoring-Addon.pdf",
        "source_page": 7,
    },
    {
        "question": "Quando si applica Replace Data Value with Object?",
        "options": [
            "Quando un dato va arricchito con altri dati o comportamenti",
            "Quando un oggetto non contiene dati",
            "Quando si elimina ogni comportamento",
            "Quando si vuole aggiungere un controllo null",
        ],
        "correct_answer": "Quando un dato va arricchito con altri dati o comportamenti",
        "source_quote": "   Un dato va arricchito con altri dati o con comportamenti",
        "source_file": "12-Refactoring-Addon.pdf",
        "source_page": 9,
    },
    {
        "question": "Secondo la legge Continuing Growth di Lehman, cosa deve accadere alle funzionalità?",
        "options": [
            "Devono essere continuamente accresciute durante la vita del software",
            "Devono restare immutate dopo la prima release",
            "Devono diminuire a ogni iterazione",
            "Devono essere sostituite da documentazione",
        ],
        "correct_answer": "Devono essere continuamente accresciute durante la vita del software",
        "source_quote": " VI Continuing        Le funzionalità del sistema debbono essere continuamente",
        "source_file": "13-Maintenance.pdf",
        "source_page": 2,
    },
    {
        "question": "Cosa afferma la legge Declining Quality di Lehman?",
        "options": [
            "La qualità degrada se il sistema non viene rigorosamente adattato",
            "La qualità cresce automaticamente a ogni release",
            "La qualità non dipende dall'ambiente lavorativo",
            "La qualità è costante nei sistemi ereditati",
        ],
        "correct_answer": "La qualità degrada se il sistema non viene rigorosamente adattato",
        "source_quote": "                      La qualità del sistema si degrada a meno che il sistema non",
        "source_file": "13-Maintenance.pdf",
        "source_page": 2,
    },
    {
        "question": "Perché i sistemi software devono cambiare durante la loro vita?",
        "options": [
            "Per restare utili",
            "Per eliminare ogni requisito",
            "Per evitare qualsiasi release",
            "Per ridurre sempre il numero di funzionalità",
        ],
        "correct_answer": "Per restare utili",
        "source_quote": "  cambiare se vogliono restare utili",
        "source_file": "13-Maintenance.pdf",
        "source_page": 2,
    },
    {
        "question": "Quando il processo di modifica dopo la consegna è detto manutenzione del software?",
        "options": [
            "Quando la transizione dallo sviluppo all'evoluzione è discontinua",
            "Quando lo stesso team resta responsabile per sempre",
            "Quando non esistono modifiche dopo la consegna",
            "Quando si usa esclusivamente TDD",
        ],
        "correct_answer": "Quando la transizione dallo sviluppo all'evoluzione è discontinua",
        "source_quote": "  la consegna è detto manutenzione del software",
        "source_file": "13-Maintenance.pdf",
        "source_page": 3,
    },
    {
        "question": "Che cosa fa la manutenzione correttiva?",
        "options": [
            "Corregge gli errori rimasti dopo il testing pre-delivery",
            "Aggiunge soltanto nuove funzionalità",
            "Adatta il software a un nuovo hardware",
            "Previene guasti non ancora riscontrati",
        ],
        "correct_answer": "Corregge gli errori rimasti dopo il testing pre-delivery",
        "source_quote": "   – Corregge gli errori rimasti dopo il testing pre-delivery",
        "source_file": "13-Maintenance.pdf",
        "source_page": 4,
    },
    {
        "question": "Che cosa fa la manutenzione perfettiva?",
        "options": [
            "Aggiunge nuove funzionalità su richiesta del cliente",
            "Corregge solo errori di compilazione",
            "Sostituisce l'hardware obsoleto",
            "Documenta esclusivamente all'occorrenza",
        ],
        "correct_answer": "Aggiunge nuove funzionalità su richiesta del cliente",
        "source_quote": "   – Aggiunge nuove funzionalità su richiesta del cliente",
        "source_file": "13-Maintenance.pdf",
        "source_page": 4,
    },
    {
        "question": "Che cosa fa la manutenzione adattiva?",
        "options": [
            "Adatta il software a un nuovo ambiente hardware o software",
            "Corregge esclusivamente requisiti errati",
            "Aggiunge soltanto test unitari",
            "Riduce il fan-in di ogni modulo",
        ],
        "correct_answer": "Adatta il software a un nuovo ambiente hardware o software",
        "source_quote": "   – Adatta a un nuovo ambiente hardware, sistema operativo o altro",
        "source_file": "13-Maintenance.pdf",
        "source_page": 4,
    },
    {
        "question": "Qual è lo scopo della manutenzione preventiva?",
        "options": [
            "Cambiare aspetti del sistema per prevenire guasti",
            "Aggiungere funzioni su richiesta del cliente",
            "Provare il sistema nell'ambiente utente",
            "Sostituire ogni sistema ereditato",
        ],
        "correct_answer": "Cambiare aspetti del sistema per prevenire guasti",
        "source_quote": "   – Cambiamento di qualche aspetto per prevenire guasti",
        "source_file": "13-Maintenance.pdf",
        "source_page": 4,
    },
    {
        "question": "Perché può essere complicato manutenere un sistema ereditato?",
        "options": [
            "Può basarsi su tecnologie e linguaggi non più usati",
            "Usa sempre tecnologie moderne",
            "Ha necessariamente una struttura perfetta",
            "Non contiene dati aziendali",
        ],
        "correct_answer": "Può basarsi su tecnologie e linguaggi non più usati",
        "source_quote": "   – Si basa su tecnologie e linguaggi che non sono più usati",
        "source_file": "13-Maintenance.pdf",
        "source_page": 5,
    },
    {
        "question": "Quale fattore aumenta il costo di manutenzione dei sistemi ereditati?",
        "options": [
            "Documentazione inadeguata",
            "Test completamente automatizzati",
            "Struttura ad alta coesione",
            "Linguaggi attuali e supportati",
        ],
        "correct_answer": "Documentazione inadeguata",
        "source_quote": "• Documentazione inadeguata",
        "source_file": "13-Maintenance.pdf",
        "source_page": 6,
    },
    {
        "question": "Perché sostituire un sistema ereditato può essere rischioso?",
        "options": [
            "Raramente esiste una specifica completa dei requisiti",
            "Esiste sempre una specifica completa",
            "Le regole aziendali sono sempre documentate",
            "Il nuovo sviluppo è privo di rischi",
        ],
        "correct_answer": "Raramente esiste una specifica completa dei requisiti",
        "source_quote": "• Raramente esiste una specifica dei requisiti completa",
        "source_file": "13-Maintenance.pdf",
        "source_page": 7,
    },
    {
        "question": "Quando conviene reingegnerizzare un sistema ereditato?",
        "options": [
            "Quando va migliorata la sua manutenibilità",
            "Quando non viene più usato e non serve",
            "Quando la qualità non si è deteriorata e non servono modifiche",
            "Quando non esiste alcun software da trasformare",
        ],
        "correct_answer": "Quando va migliorata la sua manutenibilità",
        "source_quote": "• Reingegnerizzare il sistema per migliorarne la manutenibilità",
        "source_file": "13-Maintenance.pdf",
        "source_page": 7,
    },
    {
        "question": "Quale approccio è suggerito se la documentazione va aggiornata ma le risorse sono poche?",
        "options": [
            "Documenta all'occorrenza",
            "Ridocumenta sempre tutto immediatamente",
            "Elimina ogni documento esistente",
            "Sostituisci automaticamente il sistema",
        ],
        "correct_answer": "Documenta all'occorrenza",
        "source_quote": "   Ø Utilizza un approccio “documenta all’occorrenza”",
        "source_file": "13-Maintenance.pdf",
        "source_page": 9,
    },
    {
        "question": "Qual è l'obiettivo del code restructuring?",
        "options": [
            "Trasformare vecchio software in software meglio strutturato",
            "Aumentare il numero di bug",
            "Eliminare tutte le interfacce utente",
            "Mantenere invariata una struttura degradata",
        ],
        "correct_answer": "Trasformare vecchio software in software meglio strutturato",
        "source_quote": "• L’obiettivo è trasformare un vecchio software in un",
        "source_file": "13-Maintenance.pdf",
        "source_page": 10,
    },
    {
        "question": "Su quali categorie si basa la predizione dei costi di manutenzione?",
        "options": [
            "Metriche di prodotto e metriche di processo",
            "Solo numero di utenti e release",
            "Solo test alpha e beta",
            "Solo fan-in e documentazione",
        ],
        "correct_answer": "Metriche di prodotto e metriche di processo",
        "source_quote": "La predizione dei costi di manutenzione si basa su:",
        "source_file": "13-Maintenance.pdf",
        "source_page": 12,
    },
    {
        "question": "Che cosa misura Lines of Code (LOC o KLOC)?",
        "options": [
            "La dimensione di un componente",
            "Il numero di cammini indipendenti",
            "Il numero di moduli chiamanti",
            "Il rischio del reengineering",
        ],
        "correct_answer": "La dimensione di un componente",
        "source_quote": "• Lines of Code (LOC o KLOC): misura la dimensione di",
        "source_file": "13-Maintenance.pdf",
        "source_page": 13,
    },
]
